server:
  port: 7456

vpc:
  temp-path: /Users/xuliduo/workspaces/IdeaProjects/ows-ffmpeg-demo/tmp
  ffmpeg-configs:
    video:
      bit-rate: 500
      frame-rate: 10
  huawei:
    ak: "HSG1C2TMIMBGDAYUZGR6"
    sk: "6ZYKEc1UC3b0efkJkZ417P5GJUHTZDLxamr6JmuP"
    region: "cn-north-4"
    categories:
      - politics
      - terrorism
      - porn
      - ad


logging:
  level:
    .: DEBUG
    net:
      bramp:
        ffmpeg: ERROR
